name: Generate PDF from LaTeX
on:
  push:
    branches:
      - main

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install minimal TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-base 
          sudo apt-get install -y texlive-fonts-recommended
          sudo apt-get install -y texlive-latex-extra
          sudo apt-get install -y latexmk

      - name: Compile LaTeX
        run: |
          latexmk -pdf CV.tex

      - name: Check if PDF was generated
        run: |
          if [ ! -f CV.pdf ]; then
            echo "PDF file was not generated"
            exit 1
          fi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: CV
          path: CV.pdf
